CREATE TABLE "Trail" (
          "Id" integer GENERATED BY DEFAULT AS IDENTITY,
          "Title" varchar(100) NOT NULL,
          "Description" varchar(1024) NULL,
          CONSTRAINT "PK_Trail" PRIMARY KEY ("Id")
      );