CREATE TABLE "Course" (
          "Id" integer GENERATED BY DEFAULT AS IDENTITY,
          "Title" text NOT NULL,
          "Type" varchar(50) NOT NULL,
          "Link" varchar NOT NULL,
          "Author" varchar(100) NOT NULL,
          "TrailId" integer NULL,
          CONSTRAINT "PK_Course" PRIMARY KEY ("Id"),
          CONSTRAINT "FK_Course_Trail_TrailId" FOREIGN KEY ("TrailId") REFERENCES "Trail" ("Id") ON DELETE SET NULL
      );